service: lambda-sqs-to-sns

custom:
  stage: ${opt:stage, dev}

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  memorySize: 128
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
      Resource: ${file(../arns-${self:custom.stage}.json):SQS_DLQ_ARN.value}
  environment:
    sqs_consulta: ${file(../arns-${self:custom.stage}.json):SQS_DLQ_URL.value}
    sns_dest: ${file(../arns-${self:custom.stage}.json):SNS_EMAIL_ARN.value}
    
functions:
  sqsHandler:
    handler: handler.handler
