service: aws-python3 # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: "arn:aws:sqs:us-east-1:*:SQS_principal*"

# you can overwrite defaults here
stage: dev
functions:
  inseresqs:
    handler: handler.handler
    events:
      - http:
          path: /inseresqs
          method: post
